compile_withmaven:
  image: maven:latest
    script:
    - mvn install:install-file -Dfile=lib/EXMARaLDA.jar -DgroupId=org.exmaralda -DartifactId=exmaralda -Dversion=1.10 -Dpackaging=jar  -DgeneratePom=true
    - mvn clean compile assembly:single
    
artifacts:
    expire_in: 8 week
    paths:
      - target/hzsk-corpus-services-0.1-jar-with-dependencies.jar
